# Paths
$packFolder = (Get-Item -Path "./" -Verbose).FullName
$rootFolder = Join-Path $packFolder "../"

# List of solutions
$solutions = (
    "framework",
    "modules/account",
    "modules/audit-logging",
    "modules/background-jobs",
    "modules/blogging",
    "modules/client-simulation",
    "modules/docs",
    "modules/feature-management",
    "modules/identity",
    "modules/identityserver",
    "modules/permission-management",
    "modules/setting-management",
    "modules/tenant-management",
    "modules/users"
)

# List of projects
$projects = (

    # framework
    "framework/src/Aiwins.Rocket.ApiVersioning.Abstractions",
    "framework/src/Aiwins.Rocket.AspNetCore.Authentication.JwtBearer",
    "framework/src/Aiwins.Rocket.AspNetCore.Authentication.OAuth",
    "framework/src/Aiwins.Rocket.AspNetCore",
    "framework/src/Aiwins.Rocket.AspNetCore.MultiTenancy",
    "framework/src/Aiwins.Rocket.AspNetCore.Mvc.Client",
    "framework/src/Aiwins.Rocket.AspNetCore.Mvc.Contracts",
    "framework/src/Aiwins.Rocket.AspNetCore.Mvc",
    "framework/src/Aiwins.Rocket.AspNetCore.Mvc.UI.Bootstrap",
    "framework/src/Aiwins.Rocket.AspNetCore.Mvc.UI.Bundling",
    "framework/src/Aiwins.Rocket.AspNetCore.Mvc.UI",
    "framework/src/Aiwins.Rocket.AspNetCore.Mvc.UI.MultiTenancy",
    "framework/src/Aiwins.Rocket.AspNetCore.Mvc.UI.Packages",
    "framework/src/Aiwins.Rocket.AspNetCore.Mvc.UI.Theme.Basic",
    "framework/src/Aiwins.Rocket.AspNetCore.Mvc.UI.Theme.Shared",
    "framework/src/Aiwins.Rocket.AspNetCore.Mvc.UI.Widgets",
    "framework/src/Aiwins.Rocket.AspNetCore.Serilog",
    "framework/src/Aiwins.Rocket.AspNetCore.TestBase",
    "framework/src/Aiwins.Rocket.Auditing",
    "framework/src/Aiwins.Rocket.Authorization",
    "framework/src/Aiwins.Rocket.Autofac",
    "framework/src/Aiwins.Rocket.AutoMapper",
    "framework/src/Aiwins.Rocket.BackgroundJobs.Abstractions",
    "framework/src/Aiwins.Rocket.BackgroundJobs",
    "framework/src/Aiwins.Rocket.BackgroundJobs.HangFire",
    "framework/src/Aiwins.Rocket.BackgroundJobs.RabbitMQ",
    "framework/src/Aiwins.Rocket.BackgroundJobs.Quartz",
    "framework/src/Aiwins.Rocket.BackgroundWorkers",
    "framework/src/Aiwins.Rocket.BackgroundWorkers.Quartz",
    "framework/src/Aiwins.Rocket.Caching",
    "framework/src/Aiwins.Rocket.Castle.Core",
    "framework/src/Aiwins.Rocket.Cli.Core",
    "framework/src/Aiwins.Rocket.Cli",
    "framework/src/Aiwins.Rocket.Core",
    "framework/src/Aiwins.Rocket",
    "framework/src/Aiwins.Rocket.Dapper",
    "framework/src/Aiwins.Rocket.Data",
    "framework/src/Aiwins.Rocket.Ddd.Application",
    "framework/src/Aiwins.Rocket.Ddd.Application.Contracts",
    "framework/src/Aiwins.Rocket.Ddd.Domain",
    "framework/src/Aiwins.Rocket.Emailing",
    "framework/src/Aiwins.Rocket.TextTemplating",
    "framework/src/Aiwins.Rocket.EntityFrameworkCore",
    "framework/src/Aiwins.Rocket.EntityFrameworkCore.MySQL",
    "framework/src/Aiwins.Rocket.EntityFrameworkCore.PostgreSql",
    "framework/src/Aiwins.Rocket.EntityFrameworkCore.Sqlite",
    "framework/src/Aiwins.Rocket.EntityFrameworkCore.SqlServer",
    "framework/src/Aiwins.Rocket.EventBus",
    "framework/src/Aiwins.Rocket.EventBus.RabbitMQ",
    "framework/src/Aiwins.Rocket.Features",
    "framework/src/Aiwins.Rocket.FluentValidation",
    "framework/src/Aiwins.Rocket.Guids",
    "framework/src/Aiwins.Rocket.HangFire",
    "framework/src/Aiwins.Rocket.Http.Abstractions",
    "framework/src/Aiwins.Rocket.Http.Client",
    "framework/src/Aiwins.Rocket.Http.Client.IdentityModel",
    "framework/src/Aiwins.Rocket.Http.Client.IdentityModel.Web",
    "framework/src/Aiwins.Rocket.Http",
    "framework/src/Aiwins.Rocket.IdentityModel",
    "framework/src/Aiwins.Rocket.Json",
    "framework/src/Aiwins.Rocket.Ldap",
    "framework/src/Aiwins.Rocket.Localization.Abstractions",
    "framework/src/Aiwins.Rocket.Localization",
    "framework/src/Aiwins.Rocket.MailKit",
    "framework/src/Aiwins.Rocket.MemoryDb",
    "framework/src/Aiwins.Rocket.MongoDB",
    "framework/src/Aiwins.Rocket.MultiTenancy",
    "framework/src/Aiwins.Rocket.Minify",
    "framework/src/Aiwins.Rocket.ObjectExtending",
    "framework/src/Aiwins.Rocket.ObjectMapping",
    "framework/src/Aiwins.Rocket.Quartz",
    "framework/src/Aiwins.Rocket.RabbitMQ",
    "framework/src/Aiwins.Rocket.Redis",
    "framework/src/Aiwins.Rocket.Security",
    "framework/src/Aiwins.Rocket.Serialization",
    "framework/src/Aiwins.Rocket.Settings",
    "framework/src/Aiwins.Rocket.Sms",
    "framework/src/Aiwins.Rocket.Specifications",
    "framework/src/Aiwins.Rocket.TestBase",
    "framework/src/Aiwins.Rocket.Threading",
    "framework/src/Aiwins.Rocket.Timing",
    "framework/src/Aiwins.Rocket.UI",
    "framework/src/Aiwins.Rocket.UI.Navigation",
    "framework/src/Aiwins.Rocket.Uow",
    "framework/src/Aiwins.Rocket.Validation",
    "framework/src/Aiwins.Rocket.Validation.Abstractions",
    "framework/src/Aiwins.Rocket.VirtualFileSystem",

    # modules/account
    "modules/account/src/Aiwins.Rocket.Account.Application.Contracts",
    "modules/account/src/Aiwins.Rocket.Account.Application",
    "modules/account/src/Aiwins.Rocket.Account.HttpApi.Client",
    "modules/account/src/Aiwins.Rocket.Account.HttpApi",
    "modules/account/src/Aiwins.Rocket.Account.Web",
    "modules/account/src/Aiwins.Rocket.Account.Web.IdentityServer",
        
    # modules/audit-logging
    "modules/audit-logging/src/Aiwins.Rocket.AuditLogging.Domain",
    "modules/audit-logging/src/Aiwins.Rocket.AuditLogging.Domain.Shared",
    "modules/audit-logging/src/Aiwins.Rocket.AuditLogging.EntityFrameworkCore",
    "modules/audit-logging/src/Aiwins.Rocket.AuditLogging.MongoDB",

    # modules/background-jobs
    "modules/background-jobs/src/Aiwins.Rocket.BackgroundJobs.Domain",
    "modules/background-jobs/src/Aiwins.Rocket.BackgroundJobs.Domain.Shared",
    "modules/background-jobs/src/Aiwins.Rocket.BackgroundJobs.EntityFrameworkCore",
    "modules/background-jobs/src/Aiwins.Rocket.BackgroundJobs.MongoDB",

    # modules/blogging
    "modules/blogging/src/Aiwins.Blogging.Application.Contracts",
    "modules/blogging/src/Aiwins.Blogging.Application",
    "modules/blogging/src/Aiwins.Blogging.Domain",
    "modules/blogging/src/Aiwins.Blogging.Domain.Shared",
    "modules/blogging/src/Aiwins.Blogging.EntityFrameworkCore",
    "modules/blogging/src/Aiwins.Blogging.HttpApi.Client",
    "modules/blogging/src/Aiwins.Blogging.HttpApi",
    "modules/blogging/src/Aiwins.Blogging.MongoDB",
    "modules/blogging/src/Aiwins.Blogging.Web",

    # modules/client-simulation
    "modules/client-simulation/src/Aiwins.ClientSimulation",
    "modules/client-simulation/src/Aiwins.ClientSimulation.Web",

    # modules/docs
    "modules/docs/src/Aiwins.Docs.Admin.Application.Contracts",
    "modules/docs/src/Aiwins.Docs.Admin.Application",
    "modules/docs/src/Aiwins.Docs.Admin.HttpApi.Client",
    "modules/docs/src/Aiwins.Docs.Admin.HttpApi",
    "modules/docs/src/Aiwins.Docs.Admin.Web",
    "modules/docs/src/Aiwins.Docs.Application.Contracts",
    "modules/docs/src/Aiwins.Docs.Application",
    "modules/docs/src/Aiwins.Docs.Domain",
    "modules/docs/src/Aiwins.Docs.Domain.Shared",
    "modules/docs/src/Aiwins.Docs.EntityFrameworkCore",
    "modules/docs/src/Aiwins.Docs.HttpApi.Client",
    "modules/docs/src/Aiwins.Docs.HttpApi",
    "modules/docs/src/Aiwins.Docs.MongoDB",
    "modules/docs/src/Aiwins.Docs.Web",

    # modules/feature-management
    "modules/feature-management/src/Aiwins.Rocket.FeatureManagement.Application.Contracts",
    "modules/feature-management/src/Aiwins.Rocket.FeatureManagement.Application",
    "modules/feature-management/src/Aiwins.Rocket.FeatureManagement.Domain",
    "modules/feature-management/src/Aiwins.Rocket.FeatureManagement.Domain.Shared",
    "modules/feature-management/src/Aiwins.Rocket.FeatureManagement.EntityFrameworkCore",
    "modules/feature-management/src/Aiwins.Rocket.FeatureManagement.HttpApi.Client",
    "modules/feature-management/src/Aiwins.Rocket.FeatureManagement.HttpApi",
    "modules/feature-management/src/Aiwins.Rocket.FeatureManagement.MongoDB",
    "modules/feature-management/src/Aiwins.Rocket.FeatureManagement.Web",

    # modules/identity
    "modules/identity/src/Aiwins.Rocket.Identity.Application.Contracts",
    "modules/identity/src/Aiwins.Rocket.Identity.Application",
    "modules/identity/src/Aiwins.Rocket.Identity.AspNetCore",
    "modules/identity/src/Aiwins.Rocket.Identity.Domain",
    "modules/identity/src/Aiwins.Rocket.Identity.Domain.Shared",
    "modules/identity/src/Aiwins.Rocket.Identity.EntityFrameworkCore",
    "modules/identity/src/Aiwins.Rocket.Identity.HttpApi.Client",
    "modules/identity/src/Aiwins.Rocket.Identity.HttpApi",
    "modules/identity/src/Aiwins.Rocket.Identity.MongoDB",
    "modules/identity/src/Aiwins.Rocket.Identity.Web",
    "modules/identity/src/Aiwins.Rocket.PermissionManagement.Domain.Identity",
    
    # modules/identityserver
    "modules/identityserver/src/Aiwins.Rocket.IdentityServer.Domain",
    "modules/identityserver/src/Aiwins.Rocket.IdentityServer.Domain.Shared",
    "modules/identityserver/src/Aiwins.Rocket.IdentityServer.EntityFrameworkCore",
    "modules/identityserver/src/Aiwins.Rocket.IdentityServer.MongoDB",
    "modules/identityserver/src/Aiwins.Rocket.PermissionManagement.Domain.IdentityServer",

    # modules/permission-management
    "modules/permission-management/src/Aiwins.Rocket.PermissionManagement.Application.Contracts",
    "modules/permission-management/src/Aiwins.Rocket.PermissionManagement.Application",
    "modules/permission-management/src/Aiwins.Rocket.PermissionManagement.Domain",
    "modules/permission-management/src/Aiwins.Rocket.PermissionManagement.Domain.Shared",
    "modules/permission-management/src/Aiwins.Rocket.PermissionManagement.EntityFrameworkCore",
    "modules/permission-management/src/Aiwins.Rocket.PermissionManagement.HttpApi.Client",
    "modules/permission-management/src/Aiwins.Rocket.PermissionManagement.HttpApi",
    "modules/permission-management/src/Aiwins.Rocket.PermissionManagement.MongoDB",
    # "modules/permission-management/src/Aiwins.Rocket.PermissionManagement.Web",

    # modules/setting-management
    "modules/setting-management/src/Aiwins.Rocket.SettingManagement.Domain",
    "modules/setting-management/src/Aiwins.Rocket.SettingManagement.Domain.Shared",
    "modules/setting-management/src/Aiwins.Rocket.SettingManagement.EntityFrameworkCore",
    "modules/setting-management/src/Aiwins.Rocket.SettingManagement.MongoDB",
    "modules/setting-management/src/Aiwins.Rocket.SettingManagement.Web",

    # modules/tenant-management
    "modules/tenant-management/src/Aiwins.Rocket.TenantManagement.Application.Contracts",
    "modules/tenant-management/src/Aiwins.Rocket.TenantManagement.Application",
    "modules/tenant-management/src/Aiwins.Rocket.TenantManagement.Domain",
    "modules/tenant-management/src/Aiwins.Rocket.TenantManagement.Domain.Shared",
    "modules/tenant-management/src/Aiwins.Rocket.TenantManagement.EntityFrameworkCore",
    "modules/tenant-management/src/Aiwins.Rocket.TenantManagement.HttpApi.Client",
    "modules/tenant-management/src/Aiwins.Rocket.TenantManagement.HttpApi",
    "modules/tenant-management/src/Aiwins.Rocket.TenantManagement.MongoDB",
    "modules/tenant-management/src/Aiwins.Rocket.TenantManagement.Web",

    # modules/users
    "modules/users/src/Aiwins.Rocket.Users.Abstractions",
    "modules/users/src/Aiwins.Rocket.Users.Domain",
    "modules/users/src/Aiwins.Rocket.Users.Domain.Shared",
    "modules/users/src/Aiwins.Rocket.Users.EntityFrameworkCore",
    "modules/users/src/Aiwins.Rocket.Users.MongoDB"
)